//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fortune : DbContext
    {
        public Fortune()
            : base("name=Fortune")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTE> ARTEs { get; set; }
        public virtual DbSet<IMAGEN_ARTE> IMAGEN_ARTE { get; set; }
        public virtual DbSet<UPC> UPCs { get; set; }
        public virtual DbSet<IMAGEN_ARTE_PNL> IMAGEN_ARTE_PNL { get; set; }
        public virtual DbSet<IMAGEN_ARTE_ESTILO> IMAGEN_ARTE_ESTILO { get; set; }
    }
}
