//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGEN_ARTE_ESTILO
    {
        public int IdImgArteEstilo { get; set; }
        public Nullable<int> IdEstilo { get; set; }
        public Nullable<int> StatusArt { get; set; }
        public string extensionArt { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdSummary { get; set; }
		public EstatusArteEst EstadosArteEst { get; set; }
	}
	public enum EstatusArteEst
	{
		APPROVED = 1,
		REVIEWED = 2,
		PENDING = 3,
		INHOUSE = 4
	}
}
