//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPC
    {
        public int IdUPC { get; set; }
        public Nullable<int> IdTalla { get; set; }
        public Nullable<int> IdSummary { get; set; }
        public Nullable<long> UPC1 { get; set; }
        public Nullable<int> IdEstilo { get; set; }
		public string Talla { get; set; }
	}
}
